name: hello_world_flutter
description: A Flutter login page with Google Sign-In
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
